project:
  type: website

website:
  title: The Influence of Russia/Ukraine Conflict on US Economy
  navbar:
    right:
      - icon: github
        href: https://github.com/INFO-526-F24/project-01
    left:
      - text: Project
        href: index.qmd
      - text: Proposal
        href: proposal.qmd
      - text: Code
        href: code.qmd
      - text: Presentation
        href: https://docs.google.com/presentation/d/1lm-3nYoeYGpGQEJbRSyEtHeTigeLotv2_i3r8ClHmag/edit?usp=sharing
      - text: Contract
        href: contract.qmd
      - text: About
        href: about.qmd
      - text: Dashboard
        href: https://stocksleuths.shinyapps.io/stocksleuths/

format:
  html:
    embed-resources: true
    keep-shiny: true
    theme:
      light: flatly
      dark: darkly
    toc: true

execute:
  freeze: auto
